name: STLoR CI

on: workflow_dispatch

jobs:
  checkout-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          ref: main
      - name: Upload 03_ActivityMatch.csv
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: 03_ActivityMatch.csv
          path: public_data/04_All\ States/03_ActivityMatch.csv
          retention-days: 1
  compare:
    if: ${{ !cancelled() }}
    needs: [checkout-data]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/download-artifact@v4
        with:
          name: 03_ActivityMatch.csv
      - name: Display structure of downloaded files
        run: ls -R
      - name: Install dependencies
        run: pip install .
      - name: Build dataset
        run: python stlor/main.py
      - name: Compare datasets
        run: python stlor/compare.py 03_ActivityMatch.csv public_data/04_All\ States/03_ActivityMatch.csv
      - name: Upload latest built dataset
        uses: actions/upload-artifact@v4
        with:
          name: 03_ActivityMatch_generated.csv
          path: public_data/04_All\ States/03_ActivityMatch.csv
          retention-days: 1
      - name: Upload diff
        uses: actions/upload-artifact@v4
        with:
          name: 03_ActivityMatch_diff.csv
          path: 03_ActivityMatch_diff.csv
          retention-days: 1
