name: STLoR CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          ref: main
      - name: Upload 03_ActivityMatch.csv
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: main_ActivityMatch.csv
          path: public_data/04_All\ States/03_ActivityMatch.csv
          retention-days: 1
  compare:
    if: ${{ !cancelled() }}
    needs: [checkout-data]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/download-artifact@v4
        with:
          name: main_ActivityMatch.csv
      - name: Install dependencies
        run: pip install .
      - name: Build dataset
        run: python stlor/main.py
      - name: Compare datasets
        run: python stlor/compare.py "main_ActivityMatch.csv" "public_data/04_All States/03_ActivityMatch.csv"
