name: STLoR CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install .
      - name: Copy latest output of activity match
        run: |
          git checkout origin/main -- public_data/04_All\ States/03_ActivityMatch.csv
          mv public_data/04_All\ States/03_ActivityMatch.csv main_ActivityMatch.csv
      - name: List files
        run: |
          ls
          ls public_data/04_All\ States
      - name: Build dataset
        run: python stlor/main.py
      - name: Compare datasets
        run: python stlor/compare.py "main_ActivityMatch.csv" "public_data/04_All States/03_ActivityMatch.csv"
